services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    command: bash -c 'yarn install && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && yarn start'
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - 8080:8080
    command: bash -c 'yarn install && yarn start'
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

  db:
    image: mysql:8.0.30
    environment:
      MYSQL_DATABASE: crossware
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    expose:
      - "3306"
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root
      interval: 1s
      timeout: 1s
      retries: 20
      start_period: 1s

volumes:
  backend_node_modules:
  frontend_node_modules:
